// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IsaacAPI.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20260502030350_BaseCharacter")]
    partial class BaseCharacter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaseCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BaseDamage")
                        .HasColumnType("float");

                    b.Property<double>("DamageMult")
                        .HasColumnType("float");

                    b.Property<double>("Luck")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Range")
                        .HasColumnType("float");

                    b.Property<double>("ShotSpeed")
                        .HasColumnType("float");

                    b.Property<double>("Speed")
                        .HasColumnType("float");

                    b.Property<double>("TearsUp")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("BaseCharacters");
                });

            modelBuilder.Entity("Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseCharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BaseCharacterId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Item", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<double>("DamageMult")
                        .HasColumnType("float");

                    b.Property<double>("DamageUp")
                        .HasColumnType("float");

                    b.Property<double>("FireRateUp")
                        .HasColumnType("float");

                    b.Property<double>("LuckUp")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RangeUp")
                        .HasColumnType("float");

                    b.Property<double>("ShotSpeedUp")
                        .HasColumnType("float");

                    b.Property<double>("SpeedUp")
                        .HasColumnType("float");

                    b.Property<double>("TearsUp")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Character", b =>
                {
                    b.HasOne("BaseCharacter", "BaseCharacter")
                        .WithMany()
                        .HasForeignKey("BaseCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseCharacter");
                });

            modelBuilder.Entity("Item", b =>
                {
                    b.HasOne("Character", null)
                        .WithMany("Items")
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("Character", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
